name: Production Branch Pipeline (Promotion Only)

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Generate ECR Login Token
        id: get-token
        run: |
          TOKEN=$(aws ecr get-login-password --region eu-north-1)
          echo "token=$TOKEN" >> $GITHUB_OUTPUT

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        env:
          IMAGE_VERSION: ${{ vars.IMAGE_VERSION }}
          ECR_TOKEN: ${{ steps.get-token.outputs.token }}
        with:
          host: ${{ vars.EC2_HOST }}
          username: ubuntu 
          key: ${{ secrets.EC2_SSH_KEY }}
          envs: IMAGE_VERSION,ECR_TOKEN
          script: |
            echo "$ECR_TOKEN" | docker login --username AWS --password-stdin 245987718601.dkr.ecr.eu-north-1.amazonaws.com

            mkdir -p /home/ubuntu/prod_env
            cd /home/ubuntu/prod_env

            # 1. Generate our own Nginx map perfectly
            cat << 'EOF' > nginx.conf
            events {
                worker_connections 1024;
            }
            http {
                upstream django{
                    server backend:8000;
                }
                server{
                    listen 80;
                    server_name myapp.example.com;
                    root        /var/www/myapp/html;

                    location / {
                        proxy_pass http://django;
                        proxy_set_header Host $host;
                        proxy_set_header X-Real-IP $remote_addr;
                        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                        proxy_set_header X-Forwarded-Proto $scheme;
                    }
                }
            }
            EOF

            # 2. Generate the compose file using our local nginx.conf
            cat << EOF > docker-compose.yml
            services:
              db:
                image: postgres:15
                volumes:
                  - prod_postgres_data:/var/lib/postgresql/data
                environment:
                  - POSTGRES_DB=book_shop
                  - POSTGRES_USER=postgres
                  - POSTGRES_PASSWORD=postgres

              backend:
                image: 245987718601.dkr.ecr.eu-north-1.amazonaws.com/book_shop:\$IMAGE_VERSION
                expose:
                  - "8000"
                environment:
                  - POSTGRES_DB=book_shop
                  - POSTGRES_USER=postgres
                  - POSTGRES_PASSWORD=postgres
                  - HOST=db
                depends_on:
                  - db

              nginx:
                image: nginx:latest
                ports:
                  - "80:80"
                depends_on:
                  - backend
                volumes:
                  - prod_static_volume:/app/static
                  - ./nginx.conf:/etc/nginx/nginx.conf

            volumes:
              prod_postgres_data:
              prod_static_volume:
            EOF

            docker compose -p prod down
            docker compose -p prod up -d