name: Test Branch Pipeline (Image-First)

on:
  push:
    branches:
      - test

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      image_uri: ${{ steps.build-image.outputs.image }}
      ecr_token: ${{ steps.get-token.outputs.token }}
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Build Fresh Artifact
        run: |
          cd book-shop
          export ARTIFACT_FILE="app-artifact.tar.gz"
          tar --exclude='./artifacts' -czf artifacts/$ARTIFACT_FILE .
          echo "ARTIFACT_NAME=$ARTIFACT_FILE" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Generate ECR Login Token
        id: get-token
        run: |
          TOKEN=$(aws ecr get-login-password --region eu-north-1)
          echo "token=$TOKEN" >> $GITHUB_OUTPUT

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: book_shop
          IMAGE_TAG: test-${{ github.sha }} 
        run: |
          cd book-shop
          docker build --build-arg ARTIFACT_NAME=${{ env.ARTIFACT_NAME }} -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        env:
          IMAGE_URI: ${{ needs.build-and-push.outputs.image_uri }}
          ECR_TOKEN: ${{ needs.build-and-push.outputs.ecr_token }}
        with:
          host: ${{ vars.EC2_HOST }}
          username: ubuntu 
          key: ${{ secrets.EC2_SSH_KEY }}
          envs: IMAGE_URI,ECR_TOKEN
          script: |
            echo "$ECR_TOKEN" | docker login --username AWS --password-stdin 245987718601.dkr.ecr.eu-north-1.amazonaws.com

            mkdir -p /home/ubuntu/test_env
            cd /home/ubuntu/test_env

            cat << EOF > docker-compose.yml
            services:
              db:
                image: postgres:15
                volumes:
                  - test_postgres_data:/var/lib/postgresql/data
                environment:
                  - POSTGRES_DB=book_shop
                  - POSTGRES_USER=postgres
                  - POSTGRES_PASSWORD=postgres

              backend:
                image: $IMAGE_URI
                environment:
                  - POSTGRES_DB=book_shop
                  - POSTGRES_USER=postgres
                  - POSTGRES_PASSWORD=postgres
                  - HOST=db
                depends_on:
                  - db

              nginx:
                image: nginx:latest
                ports:
                  - "8080:80"
                depends_on:
                  - backend
                volumes:
                  - test_static_volume:/static/files
                  - /home/ubuntu/devops-project/book-shop/nginx.conf:/etc/nginx/conf.d/default.conf

            volumes:
              test_postgres_data:
              test_static_volume:
            EOF

            docker compose -p test down
            docker compose -p test up -d